# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f32426be5d5819aaa7c364a3909bad0ad22cd992703265a7c42c3f1072c7067ab41371b1e34fd9a6bd39cba7bc118df1b6cf1ce0203306581b28c7e14dd95eb8

test:
  secret_key_base: d9fa335420eae82163eea17dac5e0685496716c02260d00efc91e54e74655bc16265fdf09c8975cc5864b23e0bb7d432553ef22acee4f92d9317b19dda91b30e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
